version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/cumulus-message-adapter
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: |
            npm install
            npm run test

      - save_cache:
          paths:
            - ./node_modules
          key: dependencies-{{ checksum "package.json" }}

  publish:
    working_directory: ~/cumulus-message-adapter
    steps:
      - publish_release:
          name: Publish release
          command: |
            GITHUB_TOKEN=${GITHUB_TOKEN} sh bin/release.sh
      # - publish_npm:
      #     name: Publish to NPM
      #     command: |
      #       echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      #       npm publish || echo 'npm publishing failed'

workflows:
  version: 2
  build:
    jobs:
      - build
  publish:
    jobs:
      - publish
          # filters:
          #   branches:
          #     only: master
