version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/cumulus-message-adapter
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: |
            npm install
            npm run test

      - save_cache:
          paths:
            - ./node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd ~/cumulus-message-adapter

              export VERSION=$(jq --raw-output .version package.json)
              curl -H \
                "Authorization: token $GITHUB_TOKEN" \
                -d "{\"tag_name\": \"v$VERSION\", \"target_commitsh\": \"v$VERSION\", \"name\": \"v$VERSION\"}" \
                -H "Content-Type: application/json" \
                -X POST \
                https://api.github.com/repos/nasa/cumulus-message-adapter-js/releases |grep \"url\" |grep releases |sed -e 's/.*\(https.*\)\"\,/\1/'| sed -e 's/api/uploads/'

              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
              npm publish || echo 'npm publishing failed'
            fi
