version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/cumulus-message-adapter
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: |
            npm install
            npm run test

      - save_cache:
          paths:
            - ./node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Create release
          command: |
            GITHUB_TOKEN=${GITHUB_TOKEN} sh bin/release.sh

      # - run:
      #     name: Publish to NPM
      #     command: |
      #       echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      #       npm publish || echo 'npm publishing failed'
